builds:
  -
    binary: "{{ .Env.CMD_PATH }}"
    main: ./cmd/terraform/linter/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.Version={{ .Env.VERSION }} -X main.BuildTime={{ .Env.BUILD_TIME }}
